title:
  en-US: Romain Mondon-Cancel resume
  fr-FR: CV Romain Mondon-Cancel

description:
  en-US: >-
    Data Scientist | Machine Learning Engineer with 5+ years of experience able to
    deploy, train, and serve Deep Learning models at scale looking for my next
    challenge.
  fr-FR: >-
    Data Scientist | Machine Learning Engineer avec 5+ ans d'expérience capable de
    déployer, d'entraîner et de servir des modèles de Deep Learning à l'échelle à la
    recherche de mon prochain challenge.

contact:
  title:
    en-US: Contact
  address:
    title:
      en-US: Address
      fr-FR: Adresse
    value:
      en-US:
        - 549 Fell Street Apt 10<br/>San Francisco, CA 94102

  phone:
    title:
      en-US: Cell Phone
      fr-FR: Téléphone
    value:
      en-US:
        - +1 (415) 910-0313
      fr-FR:
        - +33 (0)6 95 77 01 24

  email:
    title:
      en-US: Email
      fr-FR: Courriel
    value:
      en-US: romain.mondoncancel@gmail.com
    href:
      en-US: mailto:romain.mondoncancel@gmail.com

  website:
    title:
      en-US: Website
      fr-FR: Site web
    value:
      en-US: resume.romain.mondoncancel.com
      fr-FR: cv.romain.mondoncancel.com
    href:
      en-US: https://resume.romain.mondoncancel.com
      fr-FR: https://cv.romain.mondoncancel.com

  linkedin:
    title:
      en-US: LinkedIn
    value:
      en-US: linkedin.com/in/skasch
    href:
      en-US: https://www.linkedin.com/in/skasch/?locale=en_US
      fr-FR: https://www.linkedin.com/in/skasch/?locale=fr_FR

  github:
    title:
      en-US: GitHub
    value:
      en-US: github.com/skasch
    href:
      en-US: https://www.github.com/skasch

  codepen:
    title:
      en-US: CodePen
    value:
      en-US: codepen.io/skasch
    href:
      en-US: https://www.codepen.io/skasch

skills:
  title:
    en-US: Skills
    fr-FR: Compétences
  datascience:
    en-US: Data Science
  deeplearning:
    en-US: Deep Learning
  bi:
    en-US: Business Intelligence
  cloud:
    en-US: GCP (Cloud)
  communication:
    en-US: Communication
  projectmanagement:
    en-US: Project Management
    fr-FR: Gestion de projet
  datavisualization:
    en-US: Data Visualization
  database:
    en-US: Databases
    fr-FR: Bases de données

technologies:
  title:
    en-US: Technologies
    fr-FR: Informatique
  sql:
    en-US: SQL/HQL
  spark:
    en-US: (Py)Spark
  python:
    en-US: Python
  shell:
    en-US: Shell
  git:
    en-US: Git
  docker:
    en-US: Docker
  kubernetes:
    en-US: Kubernetes
  tensorflow:
    en-US: TensorFlow
  golang:
    en-US: Golang

languages:
  title:
    en-US: Languages
    fr-FR: Langues
  name:
    french:
      en-US: French
      fr-FR: Français
    english:
      en-US: English
      fr-FR: Anglais
    spanish:
      en-US: Spanish
      fr-FR: Espagnol
  level:
    native:
      en-US: Native
      fr-FR: Langue maternelle
    bilingual:
      en-US: Bilingual
      fr-FR: Bilingue
    intermediate:
      en-US: Intermediate
      fr-FR: Intermédiaire

misc:
  title:
    en-US: Miscellaneous
    fr-FR: Divers
  climbing:
    title:
      en-US: Sports
      fr-FR: Sport
    value:
      en-US:
        - Climbing since 2009
      fr-FR:
        - Pratique l'escalade depuis 2009
  photography:
    title:
      en-US: Hobbies
      fr-FR: Loisirs
    value:
      en-US:
        - Amateur Photographer since 2013
      fr-FR:
        - Photographe amateur depuis 2013
  awards:
    title:
      en-US: Awards
      fr-FR: Récompenses
    value:
      en-US:
        - Top 20 at 2007 Mathematics "Concours Général"
        - Ranked 7th at 2008 International Physics Olympiads selection
      fr-FR:
        - Top 20 au Concours Général de mathématiques 2007
        - 7e à la sélection des Olympiades Internationales de Physique 2008

workexperience:
  title:
    en-US: Work Experience
    fr-FR: Expérience professionnelle
  cea:
    title:
      en-US: Research Engineer Intern
      fr-FR: Ingénieur-chercheur (stage)
    subtitle:
      en-US: French Atomic Energy Commission (CEA) – Paris area
      fr-FR: Commissariat à l'énergie atomique (CEA) – région parisienne
    value:
      en-US:
        - >-
          Developed an innovative Matlab algorithm with low-level Fortran interface to
          solve the mechanical equations of heterogeneous materials subject to extreme
          pressure and temperature conditions found in the core of nuclear plants. The
          algorithm ran 5-20 times faster than the state of the art finite elements
          method.
      fr-FR:
        - >-
          Développement d'un algorithme innovant en Matlab et Fortran exécuté sur des
          serveurs de calcul dédiés pour résoudre les équations mécaniques de milieux
          hétérogènes sous fortes contraintes ; l'algorithme tournait entre 5 et 20 fois
          plus rapidement que l'algorithme de référence à l'issue du stage.
    timeline:
      en-US:
        begin: May 2012
        duration: 4 m.
        end: August 2012
      fr-FR:
        begin: Mai 2012
        duration: 4 m.
        end: Août 2012
  argonne:
    title:
      en-US: Research Engineer Intern
      fr-FR: Ingénieur-chercheur (stage)
    subtitle:
      en-US: Argonne National Laboratory – Chicago area
      fr-FR: Argonne National Laboratory – région de Chicago
    value:
      en-US:
        - >-
          Developed a Markov Chains-based algorithm based on that profile to generate
          realistic speed profiles on any itinerary, where previously simulations
          required to actually drive on the said itinerary.
        - >-
          Developed a Matlab GUI to support the Autonomie team in using this new
          feature, with a very flexible and user-friendly design displaying the
          generated speed profiles.
      fr-FR:
        - >-
          Développement d'un algorithme utilisant les chaînes de Markov pour généner des
          profils de vitesse de véhicules réalistes sur des trajets donnés.
        - >-
          Développement d'une interface graphique en Matlab pour exécuter ce précédent
          algorithme et itérer rapidement son application sur différents jeux de
          données.
    timeline:
      en-US:
        begin: Jan. 2014
        duration: 6 m.
        end: Jul. 2014
      fr-FR:
        begin: Jan. 2014
        duration: 6 m.
        end: Juil. 2014
  ubisoft1:
    title:
      en-US: Junior Data Scientist
      fr-FR: Data Scientist Junior
    subtitle:
      en-US: Ubisoft – San Francisco
    value:
      en-US:
        - >-
          Analyzed the behavior of players on multiple AAA and mobile games (millions of
          users) and created user segmentations for customer knowledge and CRM
          targeting.
        - >-
          Developed a high-end framework based on R-Shiny to quickly deploy web
          applications combining typical data and statistical visualization and
          analyses.
        - >-
          Developed a TF-IDF based document clustering application to regroup documents
          around similar topics to facilitate declarative data analysis.
      fr-FR:
        - >-
          Analyse des données comportementales des joueurs de différents jeux et
          segmentation de ces populations pour affiner la connaissance client par groupe
          plutôt qu'au global (environ 10 millions d'utilisateurs).
        - Développement d'un framework autour de <em>R-shiny</em> pour pouvoir
          rapidement déployer des applications web afin de visualiser des résultats
          d'analyses.
        - Développement d'un outil de segmentation de documents textuels utilisant la
          pondération <em>TF-IDF</em> pour faciliter le traitement de données
          déclaratives.
    timeline:
      en-US:
        begin: Jan. 2015
        duration: 1 y.
        end: Jan. 2016
      fr-FR:
        begin: Jan. 2015
        duration: 1 an
        end: Jan. 2016
  ubisoft2:
    title:
      en-US: CMK Data Scientist
      fr-FR: Data Scientist CMK
    subtitle:
      en-US: Ubisoft – Paris area
      fr-FR: Ubisoft – région parisienne
    value:
      en-US:
        - >-
          Analyzed the behavior of players on multiple AAA and mobile games (+10
          millions users) and created advanced user segmentations for customer
          knowledge, CRM targeting, and production prioritization.
        - >-
          Developed multiple data visualization tools to analyze specific kinds of data
          (d3-based Sankey diagrams, Importance-Satisfaction Matrices).
        - >-
          Animated different formations on Data Analysis, Statistics, Machine Learning
          and Python Programming.
        - >-
          Developed a Machine Learning model to describe a game based on the playing
          profiles of gamers.
      fr-FR:
        - >-
          Analyse des données comportementales des joueurs de différents jeux et
          segmentation de ces populations pour affiner la connaissance consommateur par
          groupe plutôt qu'au global (+10 millions d'utilisateurs lignes).
        - >-
          Développement et mise en production de différents outils d'analyse en
          <em>R-Shiny</em>, tels que la matrice Importance-Satisfaction, pour être
          utilisables par tous les analystes.
        - >-
          Préparation et animation de formations autour de la Data Science à destination
          d'analystes, notamment en statistiques, en Machine Learning et en Python.
    timeline:
      en-US:
        begin: Jan. 2016
        duration: 2 y.
        end: Feb. 2018
      fr-FR:
        begin: Jan. 2016
        duration: 2 ans
        end: Fév. 2018
  ubisoft3:
    title:
      en-US: Data Scientist
    subtitle:
      en-US: Ubisoft – San Francisco
    value:
      en-US:
        - >-
          Developed a TensorFlow-based Recommender System model integrated in a game
          currently in production to personalize in-game content based on user behavior.
        - >-
          Designed, built, and deployed a back-end infrastructure on GCP to expose an
          API able to train our models and return predictions.
        - >-
          Co-designed the in-game tracked events to feed our Hadoop-based database.
        - >-
          Designed, trained, deployed and tested a logistic regression model based on
          player gaming data to improve CRM targeting by up to 5%.
      fr-FR:
        - >-
          Développement d'un moteur de recommendation en TensorFlow intégré dans un jeu
          en cours de développement pour personnaliser l'expérience utilisateur en jeu
          à partir de son comportement.
        - >-
          Design, développement et déploiement d'une infrastructure serveur sur GCP pour
          exposer une API capable d'entraîner nos modèles et de retourner ses
          prédictions.
        - >-
          Co-design du tracking d'événements en jeu alimentant notre base de données
          Hadoop.
        - >-
          Design, entraînement, déploiement et test d'un modèle de régression logistique
          améliorant le targeting CRM jusqu'à 5% à partir de données de jeu.
    timeline:
      en-US:
        begin: Feb. 2018
        duration: 2 y.
        end: "–"
      fr-FR:
        begin: Fév. 2018
        duration: 2 ans
        end: "–"

education:
  title:
    en-US: Education
    fr-FR: Formation
  polytechnique:
    title:
      en-US: École polytechnique
    subtitle:
      en-US: M.S. Engineering and Business Administration – Paris area
      fr-FR: Diplôme d'ingénieur de l'École polytechnique – région parisienne
    value:
      en-US:
        - >-
          Minors in Mathematics, Energy, Applied Mathematics and Computer Science.
        - >-
          "<em>Outstanding Investment</em> award for investment in school and student
          life (2012)."
        - >-
          Built an autonomous robot to compete in the 2011 French Robotics Cup.
      fr-FR:
        - >-
          Formation généraliste en mathématiques, mathématiques appliquées, physique et
          informatique.
        - >-
          <em>Outstanding Investment</em> : a fait preuve d'un investissement
          exceptionnel dans la vie de promotion (2012).
    timeline:
      en-US:
        begin: Sep. 2009
        duration: 3 y.
        end: Aug. 2012
      fr-FR:
        begin: Sept. 2009
        duration: 3 ans
        end: Août 2012
  mines:
    title:
      en-US: Mines ParisTech
      fr-FR: École des mines ParisTech
    subtitle:
      en-US: M.S. Mechanical and Energy Engineering – Paris area
      fr-FR: Diplôme d'ingénieur des mines de Paris – région parisienne
    value:
      en-US:
        - >-
          Designed a new chassis with wheels for a quad-copter to enable ground
          movement. The drone successfully moved in the air and on the ground at the end
          of the 3-weeks project.
      fr-FR:
        - >-
          Cursus <em>Machines et Énergie</em>.
        - >-
          <em>Projet mécatronique</em> : gestion de la communication d'une équipe de 15
          étudiants pour un projet de réalisation d'une base roulante pour drone
          quadricoptère.
    timeline:
      en-US:
        begin: Sep. 2012
        duration: 2 y.
        end: Jul. 2014
      fr-FR:
        begin: Sept. 2012
        duration: 2 ans
        end: Juil. 2014
  mitx:
    title:
      en-US: MITx
      fr-FR: MITx
    subtitle:
      en-US: Graduate-level courses – <a href="www.edx.org">EdX</a>
      fr-FR: Cours de niveau master – <a href="www.edx.org">EdX</a>
    value:
      en-US:
        - >-
          <em>18.6501x Fundamentals of Statistics</em>: passed with 100%.
        - >-
          <em>6.86x Machine Learning with Python – From Linear Models to Deep
          Learning</em>: passed with 100%.
      fr-FR:
        - >-
          <em>18.6501x Fundamentals of Statistics</em>: validé avec un score de 100%.
        - >-
          <em>6.86x Machine Learning with Python – From Linear Models to Deep
          Learning</em>: validé avec un score de 100%.
    timeline:
      en-US:
        begin: Feb. 2019
        duration: 8 m.
        end: Sep. 2019
      fr-FR:
        begin: Fév. 2019
        duration: 8 m.
        end: Sept. 2019
